version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db: 
    image: postgres:latest
    restart: always
    container_name: 'postgres_nest_admin'
    environment:
      POSTGRES_DB: 'nest_admin'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
    ports:
      - 3344:5432

